name: Compatibility Build

on:
  workflow_dispatch:
  schedule:
    - cron: '5 6 * * *'

jobs:
  integration:
    strategy:
      matrix:
        version:
        - '3.1.7'
        - '3.1.8-SNAPSHOT'
        - '3.2.2-SNAPSHOT'
    name: Build against Boot ${{ matrix.version }}
    runs-on: ubuntu-latest

    steps:

    - name: Check out sources
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: 17
        cache: 'maven'

    - name: Build with Maven
      env:
        GRADLE_ENTERPRISE_CACHE_USERNAME: ${{ secrets.GRADLE_ENTERPRISE_CACHE_USER }}
        GRADLE_ENTERPRISE_CACHE_PASSWORD: ${{ secrets.GRADLE_ENTERPRISE_CACHE_PASSWORD }}
        GRADLE_ENTERPRISE_ACCESS_KEY: ${{ secrets.GRADLE_ENTERPRISE_SECRET_ACCESS_KEY }}
      run: |
        cd spring-modulith-examples
        ../mvnw -B versions:update-parent -DskipResolution=true -DparentVersion=${{ matrix.version }}
        ../mvnw -B clean verify -Pwith-preview-repos -Dspring-boot.version=${{ matrix.version }}
